# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-31 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2017, 1, 31, 10, 56, 11, 413244, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
